/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.kolkokrzyzyk;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class KolkoKrzyzyk extends javax.swing.JFrame {

    /**
     * Creates new form KolkoKrzyzyk
     */
    public KolkoKrzyzyk() {
        initComponents();
        this.setLocationRelativeTo(null);
        changeGameStatus();
        jL_points1.setText("");
        jL_points2.setText("");
        jL_points.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_map = new javax.swing.ButtonGroup();
        jPanel = new javax.swing.JPanel();
        jTF_player1_nickname = new javax.swing.JTextField();
        jL_A = new javax.swing.JLabel();
        jB_map_9 = new javax.swing.JButton();
        jB_map_8 = new javax.swing.JButton();
        jB_map_7 = new javax.swing.JButton();
        jB_map_6 = new javax.swing.JButton();
        jB_map_5 = new javax.swing.JButton();
        jB_map_4 = new javax.swing.JButton();
        jB_map_3 = new javax.swing.JButton();
        jB_map_2 = new javax.swing.JButton();
        jB_map_1 = new javax.swing.JButton();
        jTF_player2_nickname = new javax.swing.JTextField();
        jL_B = new javax.swing.JLabel();
        jL_player1_sign = new javax.swing.JLabel();
        jL_player2_sign = new javax.swing.JLabel();
        jB_start = new javax.swing.JButton();
        jB_changeSign = new javax.swing.JButton();
        jL_currMove = new javax.swing.JLabel();
        jL_points = new javax.swing.JLabel();
        jL_points1 = new javax.swing.JLabel();
        jL_points2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kółko i krzyżyk");
        setPreferredSize(new java.awt.Dimension(520, 400));
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(51, 51, 51));
        jPanel.setPreferredSize(new java.awt.Dimension(520, 400));

        jTF_player1_nickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_player1_nicknameActionPerformed(evt);
            }
        });

        jL_A.setForeground(new java.awt.Color(255, 255, 255));
        jL_A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_A.setText("Gracz 1");
        jL_A.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jB_map_9.setBackground(new java.awt.Color(153, 204, 255));
        jB_map_9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jB_map_9.setForeground(new java.awt.Color(255, 255, 255));
        buttonGroup_map.add(jB_map_9);
        jB_map_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_map_9ActionPerformed(evt);
            }
        });

        jB_map_8.setBackground(new java.awt.Color(51, 153, 255));
        jB_map_8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jB_map_8.setForeground(new java.awt.Color(255, 255, 255));
        buttonGroup_map.add(jB_map_8);
        jB_map_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_map_8ActionPerformed(evt);
            }
        });

        jB_map_7.setBackground(new java.awt.Color(153, 204, 255));
        jB_map_7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jB_map_7.setForeground(new java.awt.Color(255, 255, 255));
        buttonGroup_map.add(jB_map_7);
        jB_map_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_map_7ActionPerformed(evt);
            }
        });

        jB_map_6.setBackground(new java.awt.Color(51, 153, 255));
        jB_map_6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jB_map_6.setForeground(new java.awt.Color(255, 255, 255));
        buttonGroup_map.add(jB_map_6);
        jB_map_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_map_6ActionPerformed(evt);
            }
        });

        jB_map_5.setBackground(new java.awt.Color(153, 204, 255));
        jB_map_5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jB_map_5.setForeground(new java.awt.Color(255, 255, 255));
        buttonGroup_map.add(jB_map_5);
        jB_map_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_map_5ActionPerformed(evt);
            }
        });

        jB_map_4.setBackground(new java.awt.Color(51, 153, 255));
        jB_map_4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jB_map_4.setForeground(new java.awt.Color(255, 255, 255));
        buttonGroup_map.add(jB_map_4);
        jB_map_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_map_4ActionPerformed(evt);
            }
        });

        jB_map_3.setBackground(new java.awt.Color(153, 204, 255));
        jB_map_3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jB_map_3.setForeground(new java.awt.Color(255, 255, 255));
        buttonGroup_map.add(jB_map_3);
        jB_map_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_map_3ActionPerformed(evt);
            }
        });

        jB_map_2.setBackground(new java.awt.Color(51, 153, 255));
        jB_map_2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jB_map_2.setForeground(new java.awt.Color(255, 255, 255));
        buttonGroup_map.add(jB_map_2);
        jB_map_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_map_2ActionPerformed(evt);
            }
        });

        jB_map_1.setBackground(new java.awt.Color(153, 204, 255));
        jB_map_1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jB_map_1.setForeground(new java.awt.Color(255, 255, 255));
        buttonGroup_map.add(jB_map_1);
        jB_map_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_map_1ActionPerformed(evt);
            }
        });

        jL_B.setForeground(new java.awt.Color(255, 255, 255));
        jL_B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_B.setText("Gracz 2");
        jL_B.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jL_player1_sign.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jL_player1_sign.setForeground(new java.awt.Color(255, 255, 255));
        jL_player1_sign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_player1_sign.setText("X");

        jL_player2_sign.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jL_player2_sign.setForeground(new java.awt.Color(255, 255, 255));
        jL_player2_sign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_player2_sign.setText("O");

        jB_start.setText("START");
        jB_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_startActionPerformed(evt);
            }
        });

        jB_changeSign.setText("Zmień symbol");
        jB_changeSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_changeSignActionPerformed(evt);
            }
        });

        jL_currMove.setForeground(new java.awt.Color(255, 255, 255));
        jL_currMove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jL_points.setForeground(new java.awt.Color(255, 255, 255));
        jL_points.setText("Punkty: ");

        jL_points1.setForeground(new java.awt.Color(255, 255, 255));
        jL_points1.setText("Gracz 1:");

        jL_points2.setForeground(new java.awt.Color(255, 255, 255));
        jL_points2.setText("Gracz 2:");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jB_changeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jB_start, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jL_player1_sign, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTF_player1_nickname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addComponent(jL_A, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_currMove, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(jB_map_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jB_map_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jB_map_3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(jB_map_4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jB_map_5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jB_map_6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addComponent(jB_map_7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jB_map_8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jB_map_9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_player2_nickname, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jL_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_player2_sign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_points1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_points, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jL_points2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jL_A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_player1_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_player1_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jB_start)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_changeSign))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_B)
                            .addComponent(jL_currMove, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jTF_player2_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL_player2_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jB_map_3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB_map_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB_map_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jB_map_6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB_map_5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB_map_4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jB_map_9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB_map_8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB_map_7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(10, 10, 10)
                .addComponent(jL_points)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jL_points1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_points2)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_changeSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_changeSignActionPerformed
        changePlayerSigns();
    }//GEN-LAST:event_jB_changeSignActionPerformed

    private void jB_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_startActionPerformed
        start();
    }//GEN-LAST:event_jB_startActionPerformed

    private void jB_map_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_map_1ActionPerformed
        move(jB_map_1);
    }//GEN-LAST:event_jB_map_1ActionPerformed

    private void jB_map_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_map_2ActionPerformed
        move(jB_map_2);
    }//GEN-LAST:event_jB_map_2ActionPerformed

    private void jB_map_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_map_3ActionPerformed
        move(jB_map_3);
    }//GEN-LAST:event_jB_map_3ActionPerformed

    private void jB_map_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_map_4ActionPerformed
        move(jB_map_4);
    }//GEN-LAST:event_jB_map_4ActionPerformed

    private void jB_map_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_map_5ActionPerformed
        move(jB_map_5);
    }//GEN-LAST:event_jB_map_5ActionPerformed

    private void jB_map_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_map_6ActionPerformed
        move(jB_map_6);
    }//GEN-LAST:event_jB_map_6ActionPerformed

    private void jB_map_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_map_7ActionPerformed
        move(jB_map_7);
    }//GEN-LAST:event_jB_map_7ActionPerformed

    private void jB_map_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_map_8ActionPerformed
        move(jB_map_8);
    }//GEN-LAST:event_jB_map_8ActionPerformed

    private void jB_map_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_map_9ActionPerformed
        move(jB_map_9);
    }//GEN-LAST:event_jB_map_9ActionPerformed

    private void jTF_player1_nicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_player1_nicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_player1_nicknameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KolkoKrzyzyk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KolkoKrzyzyk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KolkoKrzyzyk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KolkoKrzyzyk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KolkoKrzyzyk().setVisible(true);
            }
        });
    }
    
    private void start() {
        addPoint("###");
        clearBoard();
        changeGameStatus();
        changeCurrPlayer();
        if(gameState) {
            jL_points1.setText("");
            jL_points2.setText("");
            jL_points.setText("");
            
            player1Points = 0;
            player2Points = 0;
        }
    }
    
    private void changeGameStatus() {
        jTF_player1_nickname.setEditable(!gameState);
        jTF_player2_nickname.setEditable(!gameState);
        
        jB_changeSign.setEnabled(!gameState);
        
        jB_map_1.setEnabled(gameState);
        jB_map_2.setEnabled(gameState);
        jB_map_3.setEnabled(gameState);
        jB_map_4.setEnabled(gameState);
        jB_map_5.setEnabled(gameState);
        jB_map_6.setEnabled(gameState);
        jB_map_7.setEnabled(gameState);
        jB_map_8.setEnabled(gameState);
        jB_map_9.setEnabled(gameState);
        
        changeActionButtonText(gameState);
        
        gameState = !gameState;
    }
    
    private void changeActionButtonText(boolean bol) {
        if(bol) jB_start.setText("STOP");
        else jB_start.setText("START");
    }
    
    private void changePlayerSigns() {
        String player1_sign = jL_player1_sign.getText();
        
        if(player1_sign.equals("X")) {
           jL_player1_sign.setText("O");
           jL_player2_sign.setText("X");
        } else {
            jL_player1_sign.setText("X");
            jL_player2_sign.setText("O");
        }
        
        changeCurrPlayer();
    }
    
    private void clearBoard() {
        jB_map_1.setText("");
        jB_map_2.setText("");
        jB_map_3.setText("");
        jB_map_4.setText("");
        jB_map_5.setText("");
        jB_map_6.setText("");
        jB_map_7.setText("");
        jB_map_8.setText("");
        jB_map_9.setText("");
        currSign = "X";
        changeCurrPlayer();
    }
    
    private void move(JButton btn) {
        String btnSign = btn.getText();
        if(btnSign.length() == 0) {
            btn.setText(""+currSign);
            changeSign();
            logic();
        }
    }
    
    private void changeSign() {
        if(currSign.equals("X")) currSign = "O";
        else currSign = "X";
        
        changeCurrPlayer();
    }
    
    private void changeCurrPlayer() {
        if(!gameState) { 
            String currPlayer = "";
            if(currSign == jL_player1_sign.getText()) {
                if(jTF_player1_nickname.getText().length() > 0) currPlayer = jTF_player1_nickname.getText();
                else currPlayer = "Gracz 1";
            } else {
                if(jTF_player2_nickname.getText().length() > 0) currPlayer = jTF_player2_nickname.getText();
                else currPlayer = "Gracz 2";
            }
            jL_currMove.setText("Ruch gracza "+currPlayer); 
        } else jL_currMove.setText("");
    }
    
    private void logic() {
        // X = 1, O = 2
        String winner = "none";
        int[][] t = new int[3][3];
        //y  x
        t[0][0] = textToInt(jB_map_1);
        t[0][1] = textToInt(jB_map_2);
        t[0][2] = textToInt(jB_map_3);
       
        t[1][0] = textToInt(jB_map_4);
        t[1][1] = textToInt(jB_map_5);
        t[1][2] = textToInt(jB_map_6);
       
        t[2][0] = textToInt(jB_map_7);
        t[2][1] = textToInt(jB_map_8);
        t[2][2] = textToInt(jB_map_9);
        
        //poziomo
        for(int i=0; i<3; i++) {
            int sum = t[i][0] + t[i][1] + t[i][2];
            if(sum == 3) winner = "X";
            else if(sum == 6) winner = "O";
        }
       
        //pionowo
        for(int i=0; i<3; i++) {
            int sum = t[0][i] + t[1][i] + t[2][i];
            if(sum == 3) winner = "X";
            else if(sum == 6) winner = "O";
        }
       
        //ukos
        int sum = t[0][0] + t[1][1] + t[2][2];
        if(sum == 3) winner = "X";
        else if(sum == 6) winner = "O";
       
        sum = t[2][0] + t[1][1] + t[0][2];
        if(sum == 3) winner = "X";
        else if(sum == 6) winner = "O";
       
        if(winner.equals("X")) {
            if(jL_player1_sign.getText().equals("X")) {
                if(jTF_player1_nickname.getText().length() == 0) winner = "Gracz 1";
                else winner = jTF_player1_nickname.getText();
            } else {
                if(jTF_player2_nickname.getText().length() == 0) winner = "Gracz 2";
                else winner = jTF_player2_nickname.getText(); 
            }
        } else if(winner.equals("O")) {
            if(jL_player1_sign.getText().equals("O")) {
                if(jTF_player1_nickname.getText().length() == 0) winner = "Gracz 1";
                else winner = jTF_player1_nickname.getText();
            } else {
                if(jTF_player2_nickname.getText().length() == 0) winner = "Gracz 2";
                else winner = jTF_player2_nickname.getText(); 
            }
        }
        if(!winner.equals("none")) win(winner);
        else{
            sum = 0;
            for(int i = 0; i < 3; i++) {
                if(t[i][0] + t[i][1] + t[i][2] < 10) sum++;
            }
            if(sum == 3) win("Remis");
        }
        
    }
   
    private void win(String winner) {
        if(!winner.equals("Remis")) {
            addPoint(winner);
            winner = "Wygrał "+winner;
        }
        JOptionPane.showMessageDialog(null, winner, "", JOptionPane.PLAIN_MESSAGE);
        clearBoard();
    }
    
    private void addPoint(String winner) {
        if(jTF_player1_nickname.equals(winner)) player1Points++;
        else if(jTF_player2_nickname.equals(winner)) player2Points++;
        else if(jL_A.equals(winner)) player1Points++;
        else if(jL_B.equals(winner)) player2Points++;
        
        String player1Nick = "Gracz 1";
        String player2Nick = "Gracz 2";
        
        if(jTF_player1_nickname.getText().length() > 0) player1Nick = jTF_player1_nickname.getText();
        if(jTF_player2_nickname.getText().length() > 0) player2Nick = jTF_player2_nickname.getText();
        
        if(winner.equals(player1Nick)) player1Points++;
        else if(winner.equals(player2Nick)) player2Points++;
        
        jL_points1.setText(player1Nick+": "+player1Points);
        jL_points2.setText(player2Nick+": "+player2Points);
        
    }
    
    private int textToInt(JButton button) {
        String text = button.getText();
        if(text.equals("X")) return 1;
        if(text.equals("O")) return 2;
        return 10;
    }
    
    int player1Points = 0;
    int player2Points = 0;
    String currSign = "X";
    boolean gameState = false;
//    String player = startingPlayer();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_map;
    private javax.swing.JButton jB_changeSign;
    private javax.swing.JButton jB_map_1;
    private javax.swing.JButton jB_map_2;
    private javax.swing.JButton jB_map_3;
    private javax.swing.JButton jB_map_4;
    private javax.swing.JButton jB_map_5;
    private javax.swing.JButton jB_map_6;
    private javax.swing.JButton jB_map_7;
    private javax.swing.JButton jB_map_8;
    private javax.swing.JButton jB_map_9;
    private javax.swing.JButton jB_start;
    private javax.swing.JLabel jL_A;
    private javax.swing.JLabel jL_B;
    private javax.swing.JLabel jL_currMove;
    private javax.swing.JLabel jL_player1_sign;
    private javax.swing.JLabel jL_player2_sign;
    private javax.swing.JLabel jL_points;
    private javax.swing.JLabel jL_points1;
    private javax.swing.JLabel jL_points2;
    private javax.swing.JPanel jPanel;
    private javax.swing.JTextField jTF_player1_nickname;
    private javax.swing.JTextField jTF_player2_nickname;
    // End of variables declaration//GEN-END:variables
}
