/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pl.com.szymon.rychter.kalkulatorbmi;

/**
 *
 * @author Szymon
 */
public class Wyglad2 extends javax.swing.JFrame {

    /**
     * Creates new form Wyglad2
     */
    public Wyglad2() {
        initComponents();
        jLabel_bmi.setText("");
        jLabel_bmi2.setText(""); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_calculatorBmi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_weight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_height = new javax.swing.JTextField();
        jButton_calculateBmi = new javax.swing.JButton();
        jLabel_bmi = new javax.swing.JLabel();
        jLabel_bmi2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel_calculatorBmi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_calculatorBmi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_calculatorBmi.setText("Kalkulator BMI");

        jLabel1.setText("Podaj wagę [kg]:");

        jTextField_weight.setText("0");

        jLabel2.setText("Podaj wzrost [cm]:");

        jTextField_height.setText("0");

        jButton_calculateBmi.setText("Oblicz");
        jButton_calculateBmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calculateBmiActionPerformed(evt);
            }
        });

        jLabel_bmi.setText("Twoje BMI wynosi: ");

        jLabel_bmi2.setText("stan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_calculatorBmi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jTextField_height)))
                    .addComponent(jButton_calculateBmi)
                    .addComponent(jLabel_bmi)
                    .addComponent(jLabel_bmi2))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_calculatorBmi)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_height)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jButton_calculateBmi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_bmi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_bmi2)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_calculateBmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calculateBmiActionPerformed
        float weight = Float.parseFloat(jTextField_weight.getText());
        float height = (Float.parseFloat(jTextField_height.getText())) / 100; // przez 100 aby bylo zamienione na metry z cm
        float bmi = weight /(float)(height*height);
        bmi = Math.round(bmi*100)/100;
        if(weight == 0 || height == 0) jLabel_bmi.setText("Proszę podać prawidłowe wartości!");
        else{
            String stan;
            //if'y bez klamer dla 1 polecenia
            if(bmi<16) stan = "wygłodzenie";
            else if(bmi<=16.99) stan = "wychudzenie";
            else if(bmi<=18.49) stan = "niedowaga";
            else if(bmi<=24.99) stan = "prawidłowa masa ciała";
            else if(bmi<=29.99) stan = "nadwaga";
            else if(bmi<=34.99) stan = "otyłość I stopnia";
            else if(bmi<=39.99) stan = "otyłość II stopnia (duża)";
            else stan = "otyłość III stopnia (chorobliwa)";
            
            jLabel_bmi.setText("Twoje BMI wynosi: "+bmi);
            jLabel_bmi2.setText(stan);
        }
    }//GEN-LAST:event_jButton_calculateBmiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wyglad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wyglad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wyglad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wyglad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wyglad2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_calculateBmi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_bmi;
    private javax.swing.JLabel jLabel_bmi2;
    private javax.swing.JLabel jLabel_calculatorBmi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_height;
    private javax.swing.JTextField jTextField_weight;
    // End of variables declaration//GEN-END:variables
}
