/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.logowanierejestracja;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Szymon
 */
public class LogowanieRejestracja extends javax.swing.JFrame {

    /**
     * Creates new form LogowanieRejestracja
     */
    public LogowanieRejestracja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel_login = new javax.swing.JPanel();
        jLabel_login = new javax.swing.JLabel();
        jTextField_login_login = new javax.swing.JTextField();
        jLabel_login_password = new javax.swing.JLabel();
        jTextField_login_password = new javax.swing.JTextField();
        jButton_login_logIn = new javax.swing.JButton();
        jLabel_login_result = new javax.swing.JLabel();
        jPanel_register = new javax.swing.JPanel();
        jLabel_register_login = new javax.swing.JLabel();
        jTextField_register_login = new javax.swing.JTextField();
        jLabel_register_email = new javax.swing.JLabel();
        jTextField_register_email = new javax.swing.JTextField();
        jLabel_register_confirmPassword = new javax.swing.JLabel();
        jLabel_register_password = new javax.swing.JLabel();
        jTextField_register_confirmPassword = new javax.swing.JTextField();
        jTextField_register_password = new javax.swing.JTextField();
        jButton_register_register = new javax.swing.JButton();
        jLabel_register_result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.setBackground(new java.awt.Color(153, 204, 255));

        jPanel_login.setBackground(new java.awt.Color(153, 204, 255));

        jLabel_login.setText("Login: ");

        jTextField_login_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_login_loginjTextField1ActionPerformed(evt);
            }
        });

        jLabel_login_password.setText("Hasło:");

        jTextField_login_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_login_passwordjTextField2ActionPerformed(evt);
            }
        });

        jButton_login_logIn.setText("Zaloguj");
        jButton_login_logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_login_logInActionPerformed(evt);
            }
        });

        jLabel_login_result.setText(" ");

        javax.swing.GroupLayout jPanel_loginLayout = new javax.swing.GroupLayout(jPanel_login);
        jPanel_login.setLayout(jPanel_loginLayout);
        jPanel_loginLayout.setHorizontalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_loginLayout.createSequentialGroup()
                        .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_login_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_login, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_loginLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_login_login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jTextField_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton_login_logIn)
                    .addComponent(jLabel_login_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel_loginLayout.setVerticalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_login, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_login_login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_login_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_login_logIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_login_result)
                .addGap(149, 149, 149))
        );

        jTabbedPane.addTab("Logowanie", jPanel_login);

        jPanel_register.setBackground(new java.awt.Color(153, 204, 255));

        jLabel_register_login.setText("Login: ");

        jTextField_register_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_register_loginActionPerformed(evt);
            }
        });

        jLabel_register_email.setText("Email:");

        jTextField_register_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_register_emailActionPerformed(evt);
            }
        });

        jLabel_register_confirmPassword.setText("Powtórz hasło:");

        jLabel_register_password.setText("Hasło");

        jTextField_register_confirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_register_confirmPasswordActionPerformed(evt);
            }
        });

        jTextField_register_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_register_passwordActionPerformed(evt);
            }
        });

        jButton_register_register.setText("Zarejestruj");
        jButton_register_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_register_registerActionPerformed(evt);
            }
        });

        jLabel_register_result.setText(" ");

        javax.swing.GroupLayout jPanel_registerLayout = new javax.swing.GroupLayout(jPanel_register);
        jPanel_register.setLayout(jPanel_registerLayout);
        jPanel_registerLayout.setHorizontalGroup(
            jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_registerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_register_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_registerLayout.createSequentialGroup()
                            .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_register_confirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(jLabel_register_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_register_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_register_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_register_login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_register_email, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_register_password, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_register_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jButton_register_register)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel_registerLayout.setVerticalGroup(
            jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_registerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_register_login, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_register_login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_register_email, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_register_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_register_password, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_register_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_register_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_register_confirmPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_register_register)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_register_result)
                .addGap(75, 75, 75))
        );

        jTabbedPane.addTab("Rejestracja", jPanel_register);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_login_loginjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_login_loginjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_login_loginjTextField1ActionPerformed

    private void jTextField_register_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_register_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_register_loginActionPerformed

    private void jTextField_register_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_register_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_register_emailActionPerformed

    private void jTextField_register_confirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_register_confirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_register_confirmPasswordActionPerformed

    private void jTextField_register_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_register_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_register_passwordActionPerformed

    private void jButton_login_logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_login_logInActionPerformed
        String login = jTextField_login_login.getText();
        String password = jTextField_login_password.getText();
        
        String result = login(login, password);
        
        jLabel_login_result.setText(result);
    }//GEN-LAST:event_jButton_login_logInActionPerformed

    private void jButton_register_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_register_registerActionPerformed
        String login = jTextField_register_login.getText();
        String email = jTextField_register_email.getText();
        String password = jTextField_register_password.getText();
        String confirmPassword = jTextField_register_confirmPassword.getText();
        
        String result = register(login, email, password, confirmPassword);
        
        jLabel_register_result.setText(result);
    }//GEN-LAST:event_jButton_register_registerActionPerformed

    private void jTextField_login_passwordjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_login_passwordjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_login_passwordjTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogowanieRejestracja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogowanieRejestracja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogowanieRejestracja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogowanieRejestracja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogowanieRejestracja().setVisible(true);
            }
        });
    }

    private String register(String login, String email, String password, String confirmPassword) {
        if(login.equals("")) return "Nie może być pustego pola login";
        if(email.equals("")) return "Nie może być pustego pola email";
        if(password.equals("")) return "Nie może być pustego pola hasło";
        if(!password.equals(confirmPassword)) return "Oba hasła muszą być takie same";
        
        try {
            FileWriter fw = new FileWriter(f, true);
            fw.write(login+";"+email+";"+password+"\n");
            fw.close();
        } catch (IOException ex) {
            System.out.println(ex);
        }
        
        return "Rejestracja się udała";
    }
    
    private String login(String login, String password) {
        if(login.equals("")) return "Nie może być pustego pola login";
        if(password.equals("")) return "Nie może być pustego pola hasło";
        
        try {
            Scanner sc = new Scanner(f);
            while (sc.hasNextLine()) {                
                String line = sc.nextLine();
                String[] data = line.split(";");
                if(data[0].equals(login) && data[2].equals(password)) return "Zalogowano pomyślnie";
            }
            
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        }
        
        return "Niepoprawne dane";
    }
    
    File f = new File("data.txt");
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_login_logIn;
    private javax.swing.JButton jButton_register_register;
    private javax.swing.JLabel jLabel_login;
    private javax.swing.JLabel jLabel_login_password;
    private javax.swing.JLabel jLabel_login_result;
    private javax.swing.JLabel jLabel_register_confirmPassword;
    private javax.swing.JLabel jLabel_register_email;
    private javax.swing.JLabel jLabel_register_login;
    private javax.swing.JLabel jLabel_register_password;
    private javax.swing.JLabel jLabel_register_result;
    private javax.swing.JPanel jPanel_login;
    private javax.swing.JPanel jPanel_register;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextField_login_login;
    private javax.swing.JTextField jTextField_login_password;
    private javax.swing.JTextField jTextField_register_confirmPassword;
    private javax.swing.JTextField jTextField_register_email;
    private javax.swing.JTextField jTextField_register_login;
    private javax.swing.JTextField jTextField_register_password;
    // End of variables declaration//GEN-END:variables
}
